import { useMemo } from "react";
import { useTranslation } from "react-i18next";

/** Admin module UI strings (users, audit, account, PMU, DPR, iJuris, backup). */
export function useAdminLabels() {
  const { t } = useTranslation();
  return useMemo(
    () => ({
      save: t("common.save"),
      saving: t("common.saving"),
      saved: t("common.saved"),
      deleted: t("common.deleted"),
      edit: t("common.edit"),
      delete: t("common.delete"),
      cancel: t("common.cancel"),
      users: {
        title: t("users.title"),
        subtitle: t("users.subtitle"),
        newUser: t("users.newUser"),
        accounts: t("users.accounts"),
        usersCount: (count) => t("users.usersCount", { count }),
        tableScroll: t("users.tableScroll"),
        colEmail: t("users.colEmail"),
        colName: t("users.colName"),
        colRole: t("users.colRole"),
        colHighCourt: t("users.colHighCourt"),
        colCreated: t("users.colCreated"),
        editUser: t("users.editUser"),
        createUser: t("users.createUser"),
        fieldEmail: t("users.fieldEmail"),
        fieldFullName: t("users.fieldFullName"),
        fieldRole: t("users.fieldRole"),
        fieldHcScope: t("users.fieldHcScope"),
        resetPasswordOptional: t("users.resetPasswordOptional"),
        initialPassword: t("users.initialPassword"),
        emailNameRequired: t("users.emailNameRequired"),
        passwordRequired: t("users.passwordRequired"),
        deleteConfirm: t("users.deleteConfirm"),
        resetConfirm: (email) => t("users.resetConfirm", { email }),
        resetPromptTitle: (email) => t("users.resetPromptTitle", { email }),
        resetSuccess: t("users.resetSuccess"),
        editBtn: t("users.edit"),
        resetPassword: t("users.resetPassword"),
        tabUsers: t("users.tabUsers"),
        tabTeams: t("users.tabTeams"),
        colTeam: t("users.colTeam"),
      },
      teams: {
        newTeam: t("users.newTeam"),
        teamsCard: t("users.teamsCard"),
        teamsCount: (count) => t("users.teamsCount", { count }),
        teamsTableScroll: t("users.teamsTableScroll"),
        colTeamName: t("users.colTeamName"),
        colDepartment: t("users.colDepartment"),
        colTeamLead: t("users.colTeamLead"),
        colMembers: t("users.colMembers"),
        createTeam: t("users.createTeam"),
        editTeam: t("users.editTeam"),
        fieldTeamName: t("users.fieldTeamName"),
        fieldDepartment: t("users.fieldDepartment"),
        fieldTeamLead: t("users.fieldTeamLead"),
        fieldMembers: t("users.fieldMembers"),
        membersHint: t("users.membersHint"),
        membersSearch: t("users.membersSearch"),
        deleteTeamConfirm: t("users.deleteTeamConfirm"),
        teamNameRequired: t("users.teamNameRequired"),
        noTeams: t("users.noTeams"),
      },
      audit: {
        title: t("audit.title"),
        subtitle: t("audit.subtitle"),
        fieldTracker: t("audit.fieldTracker"),
        fieldAction: t("audit.fieldAction"),
        rowsLoaded: (count) => t("audit.rowsLoaded", { count }),
        tableScroll: t("audit.tableScroll"),
        colTimestamp: t("audit.colTimestamp"),
        colUser: t("audit.colUser"),
        colRole: t("audit.colRole"),
        colTracker: t("audit.colTracker"),
        colAction: t("audit.colAction"),
        colHighCourt: t("audit.colHighCourt"),
        colPeriod: t("audit.colPeriod"),
        colChanges: t("audit.colChanges"),
        moreChanges: (count) => t("audit.moreChanges", { count }),
        noLogs: t("audit.noLogs"),
      },
      account: {
        passwordExpiredBanner: t("account.passwordExpiredBanner"),
        mustChangeBanner: t("account.mustChangeBanner"),
        profile: t("account.profile"),
        fieldName: t("account.fieldName"),
        fieldEmail: t("account.fieldEmail"),
        fieldRoleJurisdiction: t("account.fieldRoleJurisdiction"),
        changePasswordTitle: t("account.changePasswordTitle"),
        changePasswordSubtitle: t("account.changePasswordSubtitle"),
        currentPassword: t("account.currentPassword"),
        newPassword: t("account.newPassword"),
        confirmPassword: t("account.confirmPassword"),
        passwordMismatch: t("account.passwordMismatch"),
        passwordUpdated: t("account.passwordUpdated"),
        updatePassword: t("account.updatePassword"),
        updating: t("account.updating"),
        mandatoryChangeExpired: t("account.mandatoryChangeExpired"),
        mandatoryChangeTemp: t("account.mandatoryChangeTemp"),
        changePasswordHeading: t("account.changePasswordHeading"),
        twoFactorTitle: t("account.twoFactorTitle"),
        twoFactorTitleOptional: t("account.twoFactorTitleOptional"),
        twoFactorEnabled: t("account.twoFactorEnabled"),
        twoFactorOptionalEnabled: t("account.twoFactorOptionalEnabled"),
        twoFactorOptionalSubtitle: t("account.twoFactorOptionalSubtitle"),
        twoFactorRequired: t("account.twoFactorRequired"),
        twoFactorDisabled: t("account.twoFactorDisabled"),
        twoFactorActive: t("account.twoFactorActive"),
        twoFactorNotConfigured: t("account.twoFactorNotConfigured"),
        twoFactorSetupPrompt: t("account.twoFactorSetupPrompt"),
        begin2fa: t("account.begin2fa"),
        twoFactorStep1: t("account.twoFactorStep1"),
        twoFactorStep2: t("account.twoFactorStep2"),
        twoFactorStep3: t("account.twoFactorStep3"),
        verifyEnable: t("account.verifyEnable"),
        verifying: t("account.verifying"),
        twoFactorEnabledToast: t("account.twoFactorEnabledToast"),
        twoFactorLocked: t("account.twoFactorLocked"),
        disable2faTitle: t("account.disable2faTitle"),
        disable2faPrompt: t("account.disable2faPrompt"),
        disable2fa: t("account.disable2fa"),
        twoFactorDisabledToast: t("account.twoFactorDisabledToast"),
        qrAlt: t("account.qrAlt"),
        sessionsTitle: t("account.sessionsTitle"),
        sessionsSubtitle: t("account.sessionsSubtitle"),
        signOutOthers: t("account.signOutOthers"),
        colDevice: t("account.colDevice"),
        colIp: t("account.colIp"),
        colSignedIn: t("account.colSignedIn"),
        colLastActive: t("account.colLastActive"),
        thisDevice: t("account.thisDevice"),
        signOut: t("account.signOut"),
        revoke: t("account.revoke"),
        signedOut: t("account.signedOut"),
        sessionRevoked: t("account.sessionRevoked"),
        othersSignedOut: t("account.othersSignedOut"),
        noSessions: t("account.noSessions"),
        unknownDevice: t("account.unknownDevice"),
        accessibleRagTitle: t("account.accessibleRagTitle"),
        accessibleRagSubtitle: t("account.accessibleRagSubtitle"),
        accessibleRagDesc: t("account.accessibleRagDesc"),
        enableAccessibleRag: t("account.enableAccessibleRag"),
        apiTokensTitle: t("account.apiTokensTitle"),
        apiTokensSubtitle: t("account.apiTokensSubtitle"),
        tokenNamePlaceholder: t("account.tokenNamePlaceholder"),
        generateToken: t("account.generateToken"),
        tokenCreated: t("account.tokenCreated"),
        newTokenOnce: (token) => t("account.newTokenOnce", { token }),
        revokeTokenConfirm: t("account.revokeTokenConfirm"),
        tokenRevoked: t("account.tokenRevoked"),
        colTokenName: t("account.colTokenName"),
        colScopes: t("account.colScopes"),
        colTokenCreated: t("account.colTokenCreated"),
        noTokens: t("account.noTokens"),
      },
      pmu: {
        title: t("pmu.title"),
        subtitle: t("pmu.subtitle"),
        newTask: t("pmu.newTask"),
        editTask: t("pmu.editTask"),
        createTask: t("pmu.createTask"),
        titleRequired: t("pmu.titleRequired"),
        deleteConfirm: t("pmu.deleteConfirm"),
        noTasks: t("pmu.noTasks"),
        fieldTitle: t("pmu.fieldTitle"),
        fieldOwner: t("pmu.fieldOwner"),
        fieldStakeholder: t("pmu.fieldStakeholder"),
        fieldPriority: t("pmu.fieldPriority"),
        fieldStatus: t("pmu.fieldStatus"),
        fieldDueDate: t("pmu.fieldDueDate"),
        fieldDescription: t("pmu.fieldDescription"),
        fieldComments: t("pmu.fieldComments"),
        ownerLabel: (owner) => t("pmu.ownerLabel", { owner: owner || "—" }),
        attachments: (count) => t("pmu.attachments", { count }),
        bucketCount: (status, count) => t("pmu.bucketCount", { status, count }),
      },
      dpr: {
        title: t("dpr.title"),
        subtitle: t("dpr.subtitle"),
        newDeliverable: t("dpr.newDeliverable"),
        masterTitle: t("dpr.masterTitle"),
        milestonesCount: (count) => t("dpr.milestonesCount", { count }),
        tableScroll: t("dpr.tableScroll"),
        editDeliverable: t("dpr.editDeliverable"),
        addDeliverable: t("dpr.addDeliverable"),
        codeTitleRequired: t("dpr.codeTitleRequired"),
        deleteConfirm: t("dpr.deleteConfirm"),
        noDeliverables: t("dpr.noDeliverables"),
        fieldCode: t("dpr.fieldCode"),
        fieldTitle: t("dpr.fieldTitle"),
        fieldOwner: t("dpr.fieldOwner"),
        fieldTargetDate: t("dpr.fieldTargetDate"),
        fieldActualDate: t("dpr.fieldActualDate"),
        fieldDelayReason: t("dpr.fieldDelayReason"),
        fieldRemarks: t("dpr.fieldRemarks"),
        colCode: t("dpr.colCode"),
        colTitle: t("dpr.colTitle"),
        colOwner: t("dpr.colOwner"),
        colTargetDate: t("dpr.colTargetDate"),
        colActual: t("dpr.colActual"),
        colStatus: t("dpr.colStatus"),
        colDelayReason: t("dpr.colDelayReason"),
      },
      ijuris: {
        title: t("ijuris.title"),
        subtitle: t("ijuris.subtitle"),
        recordType: t("ijuris.recordType"),
        editJsonHint: t("ijuris.editJsonHint"),
        ingesting: t("ijuris.ingesting"),
        runIngestion: t("ijuris.runIngestion"),
        ingested: t("ijuris.ingested"),
        rejected: t("ijuris.rejected"),
        invalidJson: (message) => t("ijuris.invalidJson", { message }),
        statusTitle: t("ijuris.statusTitle"),
        pendingAccess: t("ijuris.pendingAccess"),
        statusDesc: t("ijuris.statusDesc"),
        endpointLabel: t("ijuris.endpointLabel"),
        logTitle: t("ijuris.logTitle"),
        logSubtitle: t("ijuris.logSubtitle"),
        logScroll: t("ijuris.logScroll"),
        colTimestamp: t("ijuris.colTimestamp"),
        colType: t("ijuris.colType"),
        colStatus: t("ijuris.colStatus"),
        colIngestedBy: t("ijuris.colIngestedBy"),
        colMessage: t("ijuris.colMessage"),
        noAttempts: t("ijuris.noAttempts"),
        typePhysical: t("ijuris.typePhysical"),
        typeFinancial: t("ijuris.typeFinancial"),
        typeOutcome: t("ijuris.typeOutcome"),
      },
      backup: {
        backupTitle: t("backup.backupTitle"),
        backupSubtitle: t("backup.backupSubtitle"),
        downloadBackup: t("backup.downloadBackup"),
        downloadHint: t("backup.downloadHint"),
        restoreTitle: t("backup.restoreTitle"),
        restoreSubtitle: t("backup.restoreSubtitle"),
        fieldMode: t("backup.fieldMode"),
        modeMerge: t("backup.modeMerge"),
        modeReplace: t("backup.modeReplace"),
        loadJsonFile: t("backup.loadJsonFile"),
        jsonPlaceholder: t("backup.jsonPlaceholder"),
        pasteOrLoad: t("backup.pasteOrLoad"),
        invalidJson: (message) => t("backup.invalidJson", { message }),
        missingCollections: t("backup.missingCollections"),
        restoreConfirm: (mode, replaceHint, mergeHint) =>
          t("backup.restoreConfirm", {
            mode: mode.toUpperCase(),
            replaceHint: mode === "replace" ? replaceHint : mergeHint,
          }),
        replaceHint: t("backup.replaceHint"),
        mergeHint: t("backup.mergeHint"),
        restoring: t("backup.restoring"),
        runRestore: (mode) => t("backup.runRestore", { mode }),
        restoreComplete: t("backup.restoreComplete"),
        loadedFile: (size) => t("backup.loadedFile", { size }),
        result: t("backup.result"),
        cautionTitle: t("backup.cautionTitle"),
        caution1: t("backup.caution1"),
        caution2: t("backup.caution2"),
        caution3: t("backup.caution3"),
        caution4: t("backup.caution4"),
      },
    }),
    [t],
  );
}
