import { useMemo } from "react";
import { useTranslation } from "react-i18next";

export function useDashboardLabels() {
  const { t } = useTranslation();
  return useMemo(
    () => ({
      reportingPeriod: t("dashboard.reportingPeriod"),
      allPeriods: t("dashboard.allPeriods"),
      highCourtFilter: t("dashboard.highCourtFilter"),
      allHighCourts: t("dashboard.allHighCourts"),
      componentFilter: t("dashboard.componentFilter"),
      allComponents: t("dashboard.allComponents"),
      cabinetBrief: t("dashboard.cabinetBrief"),
      physTargetSum: t("dashboard.physTargetSum"),
      physAchieved: t("dashboard.physAchieved"),
      physPercent: t("dashboard.physPercent"),
      finReleased: t("dashboard.finReleased"),
      finUtilized: t("dashboard.finUtilized"),
      finPercent: t("dashboard.finPercent"),
      indicatorsHint: (n) => t("dashboard.indicatorsHint", { count: n }),
      mixedUomHint: t("dashboard.mixedUomHint"),
      uomHint: (uom) => t("dashboard.uomHint", { uom }),
      absoluteScopeHint: (uom) => t("dashboard.absoluteScopeHint", { uom }),
      componentRowsHint: (n) => t("dashboard.componentRowsHint", { count: n }),
      varianceHint: (v) => t("dashboard.varianceHint", { value: v }),
      ragDistribution: t("dashboard.ragDistribution"),
      ragInfoAria: t("dashboard.ragInfoAria"),
      ragInfoTitle: t("dashboard.ragInfoTitle"),
      ragInfoClose: t("dashboard.ragInfoClose"),
      progressTrend: t("dashboard.progressTrend"),
      progressTrendInfoAria: t("dashboard.progressTrendInfoAria"),
      progressTrendInfoTitle: t("dashboard.progressTrendInfoTitle"),
      progressTrendInfoClose: t("dashboard.progressTrendInfoClose"),
      componentPerformance: t("dashboard.componentPerformance"),
      hcComparison: t("dashboard.hcComparison"),
      componentDrilldown: t("dashboard.componentDrilldown"),
      hcDrilldown: t("dashboard.hcDrilldown"),
      componentDrilldownTable: t("dashboard.componentDrilldownTable"),
      hcDrilldownTable: t("dashboard.hcDrilldownTable"),
      downloadExcel: t("dashboard.downloadExcel"),
      noData: t("dashboard.noData"),
      colComponent: t("dashboard.colComponent"),
      colHighCourt: t("dashboard.colHighCourt"),
      colPhysT: t("dashboard.colPhysT"),
      colPhysA: t("dashboard.colPhysA"),
      colPhysPct: t("dashboard.colPhysPct"),
      colRelCr: t("dashboard.colRelCr"),
      colUtilCr: t("dashboard.colUtilCr"),
      colUtilPct: t("dashboard.colUtilPct"),
      editLayout: t("dashboard.editLayout"),
      doneEditing: t("dashboard.doneEditing"),
      saveLayout: t("dashboard.saveLayout"),
      resetDefault: t("dashboard.resetDefault"),
      layoutSaved: t("dashboard.layoutSaved"),
      layoutSaveFailed: t("dashboard.layoutSaveFailed"),
      layoutReset: t("dashboard.layoutReset"),
      tabOverview: t("dashboard.tabOverview"),
      tabRagTrends: t("dashboard.tabRagTrends"),
      tabGeographic: t("dashboard.tabGeographic"),
      tabPerformance: t("dashboard.tabPerformance"),
      tabFinancialTracker: t("dashboard.tabFinancialTracker"),
      tabComponentTable: t("dashboard.tabComponentTable"),
      tabHcTable: t("dashboard.tabHcTable"),
      cpcScopeBanner: (hc) => t("dashboard.cpcScopeBanner", { highCourt: hc }),
      cpcHeroDesc: (hc) => t("dashboard.cpcHeroDesc", { highCourt: hc }),
      hcSummary: t("dashboard.hcSummary"),
      hcDrilldownCpc: t("dashboard.hcDrilldownCpc"),
      tabHcTableCpc: t("dashboard.tabHcTableCpc"),
      ftTarget: t("dashboard.ftTarget"),
      ftAllocated: t("dashboard.ftAllocated"),
      ftReleased: t("dashboard.ftReleased"),
      ftUtilized: t("dashboard.ftUtilized"),
      ftReleasedShort: t("dashboard.ftReleasedShort"),
      ftUtilizedShort: t("dashboard.ftUtilizedShort"),
      ftUtilPctHint: (v) => t("dashboard.ftUtilPctHint", { value: v }),
      ftHcReleased: t("dashboard.ftHcReleased"),
      ftHcUtilized: t("dashboard.ftHcUtilized"),
      ftHcReleasedSplit: t("dashboard.ftHcReleasedSplit"),
      ftHcReleasedSplitHintAll: (n) => t("dashboard.ftHcReleasedSplitHintAll", { n }),
      ftUnutilizedShort: t("dashboard.ftUnutilizedShort"),
      ftLegendReleased: t("dashboard.ftLegendReleased"),
      ftLegendUtilized: t("dashboard.ftLegendUtilized"),
      ftLegendUnutilized: t("dashboard.ftLegendUnutilized"),
      ftTop6: t("dashboard.ftTop6"),
      ftBottom6: t("dashboard.ftBottom6"),
      ftTop3: t("dashboard.ftTop3"),
      ftBottom3: t("dashboard.ftBottom3"),
      ftHcCompSliceHintTop: (n) => t("dashboard.ftHcCompSliceHintTop", { n }),
      ftHcCompSliceHintBottom: (n) => t("dashboard.ftHcCompSliceHintBottom", { n }),
      ftHcCompSliceHintTopBottom: (top, bottom) => t("dashboard.ftHcCompSliceHintTopBottom", { top, bottom }),
      ftUtilPctCompHcSliceHint: (n) => t("dashboard.ftUtilPctCompHcSliceHint", { n }),
      ftUtilPctCompHcSliceHintTop: (n) => t("dashboard.ftUtilPctCompHcSliceHintTop", { n }),
      ftUtilPctCompHcSliceHintBottom: (n) => t("dashboard.ftUtilPctCompHcSliceHintBottom", { n }),
      ftHcUtilSliceHintTop: (n) => t("dashboard.ftHcUtilSliceHintTop", { n }),
      ftHcUtilSliceHintBottom: (n) => t("dashboard.ftHcUtilSliceHintBottom", { n }),
      ftHcComponentReleased: t("dashboard.ftHcComponentReleased"),
      ftUtilPctComponentHc: t("dashboard.ftUtilPctComponentHc"),
      ftUtilPct: t("dashboard.ftUtilPct"),
      ftHcComponentUtilized: t("dashboard.ftHcComponentUtilized"),
      ftComponentUtilDonut: t("dashboard.ftComponentUtilDonut"),
      loading: t("common.loading"),
    }),
    [t],
  );
}
