import { useMemo } from "react";
import { useTranslation } from "react-i18next";

export function useDashboardLabels() {
  const { t } = useTranslation();
  return useMemo(
    () => ({
      reportingPeriod: t("dashboard.reportingPeriod"),
      allPeriods: t("dashboard.allPeriods"),
      cabinetBrief: t("dashboard.cabinetBrief"),
      physTargetSum: t("dashboard.physTargetSum"),
      physAchieved: t("dashboard.physAchieved"),
      physPercent: t("dashboard.physPercent"),
      finReleased: t("dashboard.finReleased"),
      finUtilized: t("dashboard.finUtilized"),
      finPercent: t("dashboard.finPercent"),
      indicatorsHint: (n) => t("dashboard.indicatorsHint", { count: n }),
      componentRowsHint: (n) => t("dashboard.componentRowsHint", { count: n }),
      varianceHint: (v) => t("dashboard.varianceHint", { value: v }),
      ragDistribution: t("dashboard.ragDistribution"),
      progressTrend: t("dashboard.progressTrend"),
      componentPerformance: t("dashboard.componentPerformance"),
      hcComparison: t("dashboard.hcComparison"),
      componentDrilldown: t("dashboard.componentDrilldown"),
      hcDrilldown: t("dashboard.hcDrilldown"),
      componentDrilldownTable: t("dashboard.componentDrilldownTable"),
      hcDrilldownTable: t("dashboard.hcDrilldownTable"),
      noData: t("dashboard.noData"),
      colComponent: t("dashboard.colComponent"),
      colHighCourt: t("dashboard.colHighCourt"),
      colPhysT: t("dashboard.colPhysT"),
      colPhysA: t("dashboard.colPhysA"),
      colPhysPct: t("dashboard.colPhysPct"),
      colRelCr: t("dashboard.colRelCr"),
      colUtilCr: t("dashboard.colUtilCr"),
      colUtilPct: t("dashboard.colUtilPct"),
      editLayout: t("dashboard.editLayout"),
      doneEditing: t("dashboard.doneEditing"),
      saveLayout: t("dashboard.saveLayout"),
      resetDefault: t("dashboard.resetDefault"),
      layoutSaved: t("dashboard.layoutSaved"),
      layoutSaveFailed: t("dashboard.layoutSaveFailed"),
      layoutReset: t("dashboard.layoutReset"),
      tabOverview: t("dashboard.tabOverview"),
      tabRagTrends: t("dashboard.tabRagTrends"),
      tabGeographic: t("dashboard.tabGeographic"),
      tabPerformance: t("dashboard.tabPerformance"),
      tabFinancialTracker: t("dashboard.tabFinancialTracker"),
      tabComponentTable: t("dashboard.tabComponentTable"),
      tabHcTable: t("dashboard.tabHcTable"),
      cpcScopeBanner: (hc) => t("dashboard.cpcScopeBanner", { highCourt: hc }),
      cpcHeroDesc: (hc) => t("dashboard.cpcHeroDesc", { highCourt: hc }),
      hcSummary: t("dashboard.hcSummary"),
      hcDrilldownCpc: t("dashboard.hcDrilldownCpc"),
      tabHcTableCpc: t("dashboard.tabHcTableCpc"),
      ftTarget: t("dashboard.ftTarget"),
      ftAllocated: t("dashboard.ftAllocated"),
      ftReleased: t("dashboard.ftReleased"),
      ftUtilized: t("dashboard.ftUtilized"),
      ftReleasedShort: t("dashboard.ftReleasedShort"),
      ftUtilizedShort: t("dashboard.ftUtilizedShort"),
      ftUtilPctHint: (v) => t("dashboard.ftUtilPctHint", { value: v }),
      ftHcReleased: t("dashboard.ftHcReleased"),
      ftHcUtilized: t("dashboard.ftHcUtilized"),
      ftHcComponentReleased: t("dashboard.ftHcComponentReleased"),
      ftUtilPctComponentHc: t("dashboard.ftUtilPctComponentHc"),
      ftUtilPct: t("dashboard.ftUtilPct"),
      ftTaskCountComponent: t("dashboard.ftTaskCountComponent"),
      ftHcComponentUtilized: t("dashboard.ftHcComponentUtilized"),
      ftComponentUtilDonut: t("dashboard.ftComponentUtilDonut"),
      ftWeeklyTaskStatus: t("dashboard.ftWeeklyTaskStatus"),
      ftTaskCreated: t("dashboard.ftTaskCreated"),
      ftTaskCompleted: t("dashboard.ftTaskCompleted"),
      ftTaskStillOpen: t("dashboard.ftTaskStillOpen"),
      loading: t("common.loading"),
    }),
    [t],
  );
}
