import { useMemo } from "react";
import { useTranslation } from "react-i18next";

/** Shared Master Data admin UI strings. */
export function useMasterDataLabels() {
  const { t } = useTranslation();
  return useMemo(
    () => ({
      yes: t("common.yes"),
      no: t("common.no"),
      add: t("common.add"),
      edit: t("common.edit"),
      delete: t("common.delete"),
      save: t("common.save"),
      saving: t("common.saving"),
      saved: t("common.saved"),
      deleted: t("common.deleted"),
      deleteConfirm: t("master.deleteConfirm"),
      noRecords: t("master.noRecords"),
      recordsSubtitle: (count, readOnly) =>
        t("master.recordsSubtitle", { count, readOnly: readOnly ? t("master.readOnlySuffix") : "" }),
      tableScroll: t("master.tableScroll"),
      editTitle: (entity) => t("master.editTitle", { entity }),
      addTitle: (entity) => t("master.addTitle", { entity }),
      tabHc: t("master.tabHc"),
      tabDist: t("master.tabDist"),
      tabComp: t("master.tabComp"),
      tabInd: t("master.tabInd"),
      tabSubj: t("master.tabSubj"),
      tabKpi: t("master.tabKpi"),
      tabPeriod: t("master.tabPeriod"),
      tabRag: t("master.tabRag"),
      tabSec: t("master.tabSec"),
      tabWorkflow: t("master.tabWorkflow"),
      highCourts: t("master.highCourts"),
      districts: t("master.districts"),
      districtsSubtitle: t("master.districtsSubtitle"),
      components: t("master.components"),
      physicalIndicators: t("master.physicalIndicators"),
      outcomeSubjects: t("master.outcomeSubjects"),
      outcomeKpis: t("master.outcomeKpis"),
      reportingPeriods: t("master.reportingPeriods"),
      colName: t("master.colName"),
      colActive: t("master.colActive"),
      colHighCourt: t("master.colHighCourt"),
      colDistrict: t("master.colDistrict"),
      colSeq: t("master.colSeq"),
      colCode: t("master.colCode"),
      colUom: t("master.colUom"),
      colComponent: t("master.colComponent"),
      colIndicator: t("master.colIndicator"),
      colUnit: t("master.colUnit"),
      colType: t("master.colType"),
      colSubject: t("master.colSubject"),
      colKpiId: t("master.colKpiId"),
      colKpi: t("master.colKpi"),
      colPeriodicity: t("master.colPeriodicity"),
      colGranularity: t("master.colGranularity"),
      colPeriod: t("master.colPeriod"),
      colLabel: t("master.colLabel"),
      colBaseline: t("master.colBaseline"),
      entityHighCourt: t("master.entityHighCourt"),
      entityComponent: t("master.entityComponent"),
      entityIndicator: t("master.entityIndicator"),
      entityKpi: t("master.entityKpi"),
      entitySubject: t("master.entitySubject"),
      entityPeriod: t("master.entityPeriod"),
      entityDistrict: t("master.entityDistrict"),
      fieldName: t("master.fieldName"),
      fieldCode: t("master.fieldCode"),
      fieldUom: t("master.fieldUom"),
      fieldSequence: t("master.fieldSequence"),
      fieldIndicator: t("master.fieldIndicator"),
      fieldDataType: t("master.fieldDataType"),
      fieldKpiId: t("master.fieldKpiId"),
      fieldKpi: t("master.fieldKpi"),
      fieldDescription: t("master.fieldDescription"),
      fieldPeriodicity: t("master.fieldPeriodicity"),
      fieldGranularity: t("master.fieldGranularity"),
      fieldOutcomeType: t("master.fieldOutcomeType"),
      fieldValueType: t("master.fieldValueType"),
      fieldSubjectName: t("master.fieldSubjectName"),
      fieldPeriod: t("master.fieldPeriod"),
      fieldDisplayLabel: t("master.fieldDisplayLabel"),
      fieldIsBaseline: t("master.fieldIsBaseline"),
      fieldDistrictName: t("master.fieldDistrictName"),
      ragTitle: t("master.ragTitle"),
      ragSubtitle: t("master.ragSubtitle"),
      greenMin: t("master.greenMin"),
      amberMin: t("master.amberMin"),
      saveThresholds: t("master.saveThresholds"),
      ragUpdated: t("master.ragUpdated"),
      ipTitle: t("master.ipTitle"),
      ipSubtitle: t("master.ipSubtitle"),
      ipEnable: t("master.ipEnable"),
      ipCidrs: t("master.ipCidrs"),
      ipPlaceholder: t("master.ipPlaceholder"),
      saveAllowlist: t("master.saveAllowlist"),
      ipUpdated: t("master.ipUpdated"),
      workflowTitle: t("master.workflowTitle"),
      workflowSubtitle: t("master.workflowSubtitle"),
      graceDays: t("master.graceDays"),
      slaDueDay: t("master.slaDueDay"),
      dashboardRequireApproval: t("master.dashboardRequireApproval"),
      saveSettings: t("master.saveSettings"),
      workflowSaved: t("master.workflowSaved"),
      overrideTitle: t("master.overrideTitle"),
      overrideSubtitle: t("master.overrideSubtitle"),
      overrideHours: t("master.overrideHours"),
      fieldReason: t("master.fieldReason"),
      applyOverride: t("master.applyOverride"),
      applying: t("master.applying"),
      overrideRequired: t("master.overrideRequired"),
      overrideSuccess: (until) => t("master.overrideSuccess", { until }),
    }),
    [t],
  );
}
