import { useMemo } from "react";
import { useTranslation } from "react-i18next";

/** Shared Schedules & Outbox admin UI strings. */
export function useSchedulesLabels() {
  const { t } = useTranslation();
  return useMemo(
    () => ({
      yes: t("common.yes"),
      no: t("common.no"),
      jobsTitle: t("schedules.jobsTitle"),
      jobsSubtitle: t("schedules.jobsSubtitle"),
      colJobName: t("schedules.colJobName"),
      colNextRun: t("schedules.colNextRun"),
      colTrigger: t("schedules.colTrigger"),
      runNow: t("schedules.runNow"),
      noJobs: t("schedules.noJobs"),
      deliveriesTitle: t("schedules.deliveriesTitle"),
      deliveriesScroll: t("schedules.deliveriesScroll"),
      colTimestamp: t("schedules.colTimestamp"),
      colJob: t("schedules.colJob"),
      colPeriod: t("schedules.colPeriod"),
      colRecipients: t("schedules.colRecipients"),
      colStatus: t("schedules.colStatus"),
      noDeliveries: t("schedules.noDeliveries"),
      outboxTitle: t("schedules.outboxTitle"),
      outboxSubtitleSmtp: t("schedules.outboxSubtitleSmtp"),
      outboxSubtitleMock: t("schedules.outboxSubtitleMock"),
      drainNow: t("schedules.drainNow"),
      outboxScroll: t("schedules.outboxScroll"),
      colTo: t("schedules.colTo"),
      colSubject: t("schedules.colSubject"),
      outboxEmpty: t("schedules.outboxEmpty"),
      briefTriggered: t("schedules.briefTriggered"),
      drainSuccess: (sent, failed) => t("schedules.drainSuccess", { sent, failed }),
      webhooksTitle: t("schedules.webhooksTitle"),
      webhooksSubtitle: t("schedules.webhooksSubtitle"),
      fieldName: t("schedules.fieldName"),
      fieldUrl: t("schedules.fieldUrl"),
      fieldSecret: t("schedules.fieldSecret"),
      fieldEvents: t("schedules.fieldEvents"),
      addWebhook: t("schedules.addWebhook"),
      webhooksScroll: t("schedules.webhooksScroll"),
      colWebhookName: t("schedules.colWebhookName"),
      colWebhookUrl: t("schedules.colWebhookUrl"),
      colWebhookEvents: t("schedules.colWebhookEvents"),
      colWebhookActive: t("schedules.colWebhookActive"),
      noWebhooks: t("schedules.noWebhooks"),
      recentOutbox: t("schedules.recentOutbox"),
      webhookOutboxScroll: t("schedules.webhookOutboxScroll"),
      colTime: t("schedules.colTime"),
      colEvent: t("schedules.colEvent"),
      colHttp: t("schedules.colHttp"),
      webhookOutboxEmpty: t("schedules.webhookOutboxEmpty"),
      nameUrlRequired: t("schedules.nameUrlRequired"),
      webhookCreated: t("schedules.webhookCreated"),
      deleteWebhookConfirm: t("schedules.deleteWebhookConfirm"),
      deleted: t("common.deleted"),
    }),
    [t],
  );
}
