import { useMemo } from "react";
import { useTranslation } from "react-i18next";

/** Task Management module UI strings. */
export function useTaskLabels() {
  const { t } = useTranslation();
  return useMemo(
    () => ({
      common: {
        loading: t("tasks.common.loading"),
        noTasks: t("tasks.common.noTasks"),
        createTask: t("tasks.common.createTask"),
        creating: t("tasks.common.creating"),
        cancel: t("common.cancel"),
        select: t("common.select"),
        back: t("tasks.common.back"),
        search: t("tasks.common.search"),
        previous: t("tasks.common.previous"),
        next: t("tasks.common.next"),
        page: (n) => t("tasks.common.page", { n }),
        exportCsv: t("tasks.common.exportCsv"),
        exportXlsx: t("tasks.common.exportXlsx"),
        exportPdf: t("tasks.common.exportPdf"),
        unassigned: t("tasks.common.unassigned"),
        download: t("tasks.common.download"),
        post: t("tasks.common.post"),
        remarksOptional: t("tasks.common.remarksOptional"),
        assignmentNotes: t("tasks.common.assignmentNotes"),
      },
      layout: {
        commandCentreTitle: t("tasks.layout.commandCentreTitle"),
        taskManagement: t("tasks.layout.taskManagement"),
        navLabel: t("tasks.layout.navLabel"),
        appSelector: t("tasks.layout.appSelector"),
        pmisApp: t("tasks.layout.pmisApp"),
        signOut: t("nav.signOut"),
        toggleTheme: t("tasks.layout.toggleTheme"),
        nav: {
          commandCentre: t("tasks.layout.nav.commandCentre"),
          workbench: t("tasks.layout.nav.workbench"),
          myTasks: t("tasks.layout.nav.myTasks"),
          allTasks: t("tasks.layout.nav.allTasks"),
          reports: t("tasks.layout.nav.reports"),
          configuration: t("tasks.layout.nav.configuration"),
          auditorOverview: t("tasks.layout.nav.auditorOverview"),
        },
      },
      table: {
        listAria: t("tasks.table.listAria"),
        code: t("tasks.table.code"),
        title: t("tasks.table.title"),
        priority: t("tasks.table.priority"),
        status: t("tasks.table.status"),
        owner: t("tasks.table.owner"),
        due: t("tasks.table.due"),
        sla: t("tasks.table.sla"),
      },
      appSelector: {
        initialising: t("tasks.appSelector.initialising"),
        signedInAs: (name, role) => t("tasks.appSelector.signedInAs", { name, role }),
        chooseWorkspace: t("tasks.appSelector.chooseWorkspace"),
        subtitle: t("tasks.appSelector.subtitle"),
        taskTitle: t("tasks.appSelector.taskTitle"),
        taskDesc: t("tasks.appSelector.taskDesc"),
        openTask: t("tasks.appSelector.openTask"),
        appTitle: t("tasks.appSelector.appTitle"),
        appDesc: t("tasks.appSelector.appDesc"),
        openApp: t("tasks.appSelector.openApp"),
        directLinks: t("tasks.appSelector.directLinks"),
        taskModule: t("tasks.appSelector.taskModule"),
      },
      manager: {
        loading: t("tasks.manager.loading"),
        title: t("tasks.manager.title"),
        subtitle: t("tasks.manager.subtitle"),
        kpiTotal: t("tasks.manager.kpiTotal"),
        kpiUnassigned: t("tasks.manager.kpiUnassigned"),
        kpiInProgress: t("tasks.manager.kpiInProgress"),
        kpiSubmitted: t("tasks.manager.kpiSubmitted"),
        kpiSlaBreached: t("tasks.manager.kpiSlaBreached"),
        kpiHighPriority: t("tasks.manager.kpiHighPriority"),
        kpiManagerPending: t("tasks.manager.kpiManagerPending"),
        kpiClosedMonth: t("tasks.manager.kpiClosedMonth"),
        pendingApproval: t("tasks.manager.pendingApproval"),
        pendingApprovalSub: t("tasks.manager.pendingApprovalSub"),
        unassignedPool: t("tasks.manager.unassignedPool"),
        unassignedPoolSub: t("tasks.manager.unassignedPoolSub"),
        escalations: t("tasks.manager.escalations"),
        escalationsSub: t("tasks.manager.escalationsSub"),
        byModule: t("tasks.manager.byModule"),
        byModuleSub: t("tasks.manager.byModuleSub"),
      },
      lead: {
        loading: t("tasks.lead.loading"),
        title: t("tasks.lead.title"),
        subtitle: t("tasks.lead.subtitle"),
        kpiReceived: t("tasks.lead.kpiReceived"),
        kpiPendingDist: t("tasks.lead.kpiPendingDist"),
        kpiAssigned: t("tasks.lead.kpiAssigned"),
        kpiInProgress: t("tasks.lead.kpiInProgress"),
        kpiSubmitted: t("tasks.lead.kpiSubmitted"),
        kpiRework: t("tasks.lead.kpiRework"),
        kpiSlaRisk: t("tasks.lead.kpiSlaRisk"),
        kpiProposed: t("tasks.lead.kpiProposed"),
        submittedCard: t("tasks.lead.submittedCard"),
        submittedCardSub: t("tasks.lead.submittedCardSub"),
        proposedCard: t("tasks.lead.proposedCard"),
        proposedCardSub: t("tasks.lead.proposedCardSub"),
      },
      member: {
        loading: t("tasks.member.loading"),
        title: t("tasks.member.title"),
        subtitle: t("tasks.member.subtitle"),
        kpiOpen: t("tasks.member.kpiOpen"),
        kpiDueToday: t("tasks.member.kpiDueToday"),
        kpiOverdue: t("tasks.member.kpiOverdue"),
        kpiInProgress: t("tasks.member.kpiInProgress"),
        kpiRework: t("tasks.member.kpiRework"),
        kpiSubmitted: t("tasks.member.kpiSubmitted"),
        kpiProposed: t("tasks.member.kpiProposed"),
        recentCard: t("tasks.member.recentCard"),
        recentCardSub: t("tasks.member.recentCardSub"),
      },
      list: {
        title: t("tasks.list.title"),
        tasksCount: (count) => t("tasks.list.tasksCount", { count }),
        filters: t("tasks.list.filters"),
        allStatuses: t("tasks.list.allStatuses"),
        allPriorities: t("tasks.list.allPriorities"),
      },
      bulk: {
        selected: (n) => t("tasks.bulk.selected", { count: n }),
        selectAll: t("tasks.bulk.selectAll"),
        selectTask: (code) => t("tasks.bulk.selectTask", { code }),
        assignLead: t("tasks.bulk.assignLead"),
        assignMember: t("tasks.bulk.assignMember"),
        cancel: t("tasks.bulk.cancel"),
        cancelReason: t("tasks.bulk.cancelReason"),
        cancelPlaceholder: t("tasks.bulk.cancelPlaceholder"),
        clear: t("tasks.bulk.clear"),
        leadDone: (n) => t("tasks.bulk.leadDone", { count: n }),
        memberDone: (n) => t("tasks.bulk.memberDone", { count: n }),
        cancelDone: (n) => t("tasks.bulk.cancelDone", { count: n }),
        partialFail: (n) => t("tasks.bulk.partialFail", { count: n }),
      },
      create: {
        title: t("tasks.create.title"),
        titleRequired: t("tasks.create.titleRequired"),
        titleField: t("tasks.create.titleField"),
        descriptionField: t("tasks.create.descriptionField"),
        category: t("tasks.create.category"),
        priority: t("tasks.create.priority"),
        module: t("tasks.create.module"),
        project: t("tasks.create.project"),
        department: t("tasks.create.department"),
        dueDate: t("tasks.create.dueDate"),
        assignLead: t("tasks.create.assignLead"),
        assignMember: t("tasks.create.assignMember"),
        evidenceRequired: t("tasks.create.evidenceRequired"),
        managerApproval: t("tasks.create.managerApproval"),
        instructions: t("tasks.create.instructions"),
        created: (code) => t("tasks.create.created", { code }),
      },
      assignment: {
        title: t("tasks.assignment.title"),
        assignReassign: t("tasks.assignment.assignReassign"),
        teamLead: t("tasks.assignment.teamLead"),
        teamMember: t("tasks.assignment.teamMember"),
        assignLeadBtn: t("tasks.assignment.assignLeadBtn"),
        assignMemberBtn: t("tasks.assignment.assignMemberBtn"),
        selectLead: t("tasks.assignment.selectLead"),
        selectMember: t("tasks.assignment.selectMember"),
        leadAssigned: t("tasks.assignment.leadAssigned"),
        memberAssigned: t("tasks.assignment.memberAssigned"),
        currentLead: (name) => t("tasks.assignment.currentLead", { name }),
        currentMember: (name) => t("tasks.assignment.currentMember", { name }),
      },
      detail: {
        loading: t("tasks.detail.loading"),
        notFound: t("tasks.detail.notFound"),
        ownerDue: (owner, due) => t("tasks.detail.ownerDue", { owner, due }),
        rejectPlaceholder: t("tasks.detail.rejectPlaceholder"),
        tabs: {
          overview: t("tasks.detail.tabs.overview"),
          assignment: t("tasks.detail.tabs.assignment"),
          evidence: t("tasks.detail.tabs.evidence"),
          approval: t("tasks.detail.tabs.approval"),
          comments: t("tasks.detail.tabs.comments"),
          audit: t("tasks.detail.tabs.audit"),
          subtasks: t("tasks.detail.tabs.subtasks"),
          logHours: t("tasks.detail.tabs.logHours"),
          dependency: t("tasks.detail.tabs.dependency"),
          statusTimeline: t("tasks.detail.tabs.statusTimeline"),
          issues: t("tasks.detail.tabs.issues"),
          activity: t("tasks.detail.tabs.activity"),
        },
        actions: {
          accept: t("tasks.detail.actions.accept"),
          start: t("tasks.detail.actions.start"),
          updateProgress: t("tasks.detail.actions.updateProgress"),
          submitApproval: t("tasks.detail.actions.submitApproval"),
          acceptProposed: t("tasks.detail.actions.acceptProposed"),
          rejectProposed: t("tasks.detail.actions.rejectProposed"),
          verify: t("tasks.detail.actions.verify"),
          reject: t("tasks.detail.actions.reject"),
          approveClosure: t("tasks.detail.actions.approveClosure"),
          rejectClosure: t("tasks.detail.actions.rejectClosure"),
          subtask: t("tasks.detail.actions.subtask"),
          escalate: t("tasks.detail.actions.escalate"),
          markBlocked: t("tasks.detail.actions.markBlocked"),
        },
        toast: {
          accepted: t("tasks.detail.toast.accepted"),
          started: t("tasks.detail.toast.started"),
          progressUpdated: t("tasks.detail.toast.progressUpdated"),
          submitted: t("tasks.detail.toast.submitted"),
          proposedAccepted: t("tasks.detail.toast.proposedAccepted"),
          rejected: t("tasks.detail.toast.rejected"),
          verified: t("tasks.detail.toast.verified"),
          rework: t("tasks.detail.toast.rework"),
          closed: t("tasks.detail.toast.closed"),
          commentAdded: t("tasks.detail.toast.commentAdded"),
          evidenceUploaded: t("tasks.detail.toast.evidenceUploaded"),
          escalated: t("tasks.detail.toast.escalated"),
          blocked: t("tasks.detail.toast.blocked"),
          infoSaved: t("tasks.detail.toast.infoSaved", { defaultValue: "Task information saved" }),
        },
        actionRemarksPlaceholder: t("tasks.detail.actionRemarksPlaceholder"),
        overview: {
          moduleProject: (module, project) => t("tasks.detail.overview.moduleProject", { module, project }),
          categorySource: (category, source) => t("tasks.detail.overview.categorySource", { category, source }),
          progressEvidence: (progress, evidence) => t("tasks.detail.overview.progressEvidence", { progress, evidence }),
          instructions: (text) => t("tasks.detail.overview.instructions", { text }),
        },
        assignmentCard: {
          lead: (name) => t("tasks.detail.assignmentCard.lead", { name }),
          member: (name) => t("tasks.detail.assignmentCard.member", { name }),
          createdBy: (name) => t("tasks.detail.assignmentCard.createdBy", { name }),
        },
        evidence: {
          upload: t("tasks.detail.evidence.upload"),
        },
        checklist: {
          title: t("tasks.detail.checklist.title"),
          resolution_matches: t("tasks.detail.checklist.resolution_matches"),
          evidence_uploaded: t("tasks.detail.checklist.evidence_uploaded"),
          evidence_relevant: t("tasks.detail.checklist.evidence_relevant"),
          no_dependency_pending: t("tasks.detail.checklist.no_dependency_pending"),
          sla_checked: t("tasks.detail.checklist.sla_checked"),
        },
        comments: {
          placeholder: t("tasks.detail.comments.placeholder"),
        },
        subtasks: t("tasks.detail.subtasks"),
        approvalHistory: t("tasks.detail.approvalHistory"),
        auditTrail: t("tasks.detail.auditTrail"),
        taskInformation: t("tasks.detail.taskInformation"),
        highCourtsFilter: t("tasks.detail.highCourtsFilter"),
        allHighCourts: t("tasks.detail.allHighCourts"),
        byCreator: (name) => t("tasks.detail.byCreator", { name }),
        linkedModule: t("tasks.detail.linkedModule"),
        saveTaskInfo: t("tasks.detail.saveTaskInfo"),
        addSubtask: t("tasks.detail.addSubtask"),
        onlySubtasks: t("tasks.detail.onlySubtasks"),
        daysToGo: (count) => t("tasks.detail.daysToGo", { count }),
        fields: {
          associatedTeam: t("tasks.detail.fields.associatedTeam"),
          owner: t("tasks.detail.fields.owner"),
          workHours: t("tasks.detail.fields.workHours"),
          status: t("tasks.detail.fields.status"),
          dueDate: t("tasks.detail.fields.dueDate"),
          priority: t("tasks.detail.fields.priority"),
          tags: t("tasks.detail.fields.tags"),
          reminder: t("tasks.detail.fields.reminder"),
          billingType: t("tasks.detail.fields.billingType"),
          fundTarget: t("tasks.detail.fields.fundTarget"),
          hardwareCount: t("tasks.detail.fields.hardwareCount"),
          fundsUtilised: t("tasks.detail.fields.fundsUtilised"),
          utilisationPct: t("tasks.detail.fields.utilisationPct"),
          startDate: t("tasks.detail.fields.startDate"),
          duration: t("tasks.detail.fields.duration"),
          completionPct: t("tasks.detail.fields.completionPct"),
          recurrence: t("tasks.detail.fields.recurrence"),
          component: t("tasks.detail.fields.component"),
          fundAllocated: t("tasks.detail.fields.fundAllocated"),
          fundsReleased: t("tasks.detail.fields.fundsReleased"),
          highCourtName: t("tasks.detail.fields.highCourtName"),
        },
      },
      reports: {
        loading: t("tasks.reports.loading"),
        title: t("tasks.reports.title"),
        subtitle: t("tasks.reports.subtitle"),
        kpiTotal: t("tasks.reports.kpiTotal"),
        kpiSlaBreached: t("tasks.reports.kpiSlaBreached"),
        kpiPending: t("tasks.reports.kpiPending"),
        kpiRework: t("tasks.reports.kpiRework"),
        kpiEscalated: t("tasks.reports.kpiEscalated"),
        kpiClosed: t("tasks.reports.kpiClosed"),
        byStatus: t("tasks.reports.byStatus"),
        byPriority: t("tasks.reports.byPriority"),
        byModule: t("tasks.reports.byModule"),
      },
      config: {
        title: t("tasks.config.title"),
        subtitle: t("tasks.config.subtitle"),
        slaHours: t("tasks.config.slaHours"),
        categories: t("tasks.config.categories"),
        teamsDepartments: t("tasks.config.teamsDepartments"),
        teamsDepartmentsHint: t("tasks.config.teamsDepartmentsHint"),
        apiConfig: t("tasks.config.apiConfig"),
        apiHint: t("tasks.config.apiHint"),
      },
      auditor: {
        loading: t("tasks.auditor.loading"),
        title: t("tasks.auditor.title"),
        subtitle: t("tasks.auditor.subtitle"),
        recentTasks: t("tasks.auditor.recentTasks"),
        recentTasksSub: t("tasks.auditor.recentTasksSub"),
      },
    }),
    [t],
  );
}
