import { useMemo } from "react";
import { useTranslation } from "react-i18next";

/** Shared tracker UI strings for Physical / Financial / Outcome pages. */
export function useTrackerLabels() {
  const { t } = useTranslation();
  return useMemo(
    () => ({
      highCourt: t("tracker.highCourt"),
      district: t("tracker.district"),
      hcLevel: t("tracker.hcLevel"),
      component: t("tracker.component"),
      indicator: t("tracker.indicator"),
      period: t("tracker.period"),
      target: t("tracker.target"),
      achieved: t("tracker.achieved"),
      percent: t("tracker.percent"),
      rag: t("tracker.rag"),
      remarks: t("tracker.remarks"),
      anomalyBadge: t("tracker.anomalyBadge"),
      reportingMonth: t("tracker.reportingMonth"),
      districtOptional: t("tracker.districtOptional"),
      tableFilter: t("tracker.tableFilter"),
      allDistricts: t("tracker.allDistricts"),
      hcLevelOnly: t("tracker.hcLevelOnly"),
      remarksOptional: t("tracker.remarksOptional"),
      achievedCumulative: t("tracker.achievedCumulative"),
      targetAdmin: t("tracker.targetAdmin"),
      entryUpdateOnlyHint: t("tracker.entryUpdateOnlyHint"),
      dataEntry: t("tracker.dataEntry"),
      dataEntrySubtitle: t("tracker.dataEntrySubtitle"),
      physicalEntries: t("tracker.physicalEntries"),
      exportBulk: t("tracker.exportBulk"),
      exportBulkSubtitle: t("tracker.exportBulkSubtitle"),
      exportExcel: t("tracker.exportExcel"),
      exportPdf: t("tracker.exportPdf"),
      saveEntry: t("tracker.saveEntry"),
      saving: t("tracker.saving"),
      initialize: t("tracker.initialize"),
      initializing: t("tracker.initializing"),
      initRows: t("tracker.initRows"),
      dismiss: t("tracker.dismiss"),
      draftRestored: t("tracker.draftRestored"),
      keep: t("tracker.keep"),
      discard: t("tracker.discard"),
      noEntries: t("tracker.noEntries"),
      selectRequired: t("tracker.selectRequired"),
      selectHcPeriod: t("tracker.selectHcPeriod"),
      selectHcComponentPeriod: t("tracker.selectHcComponentPeriod"),
      saved: t("tracker.saved"),
      initPrompt: (hc, period) => t("tracker.initPrompt", { hc, period }),
      finInitPrompt: (hc, period) => t("tracker.finInitPrompt", { hc, period }),
      outcomeInitPrompt: (hc, period) => t("tracker.outcomeInitPrompt", { hc, period }),
      initComponentRows: t("tracker.initComponentRows"),
      initKpiRows: t("tracker.initKpiRows"),
      initSuccess: (created, skipped) => t("tracker.initSuccess", { created, skipped }),
      entriesSubtitle: (total) => t("tracker.entriesSubtitle", { count: total }),
      paginationRange: (from, to, total) => t("tracker.paginationRange", { from, to, total }),
      paginationPage: (page, totalPages) => t("tracker.paginationPage", { page, totalPages }),
      // Financial
      finEntry: t("tracker.finEntry"),
      finEntrySubtitle: t("tracker.finEntrySubtitle"),
      finEntrySubtitleCpc: t("tracker.finEntrySubtitleCpc"),
      finEntries: t("tracker.finEntries"),
      fundTarget: t("tracker.fundTarget"),
      fundAllocated: t("tracker.fundAllocated"),
      fundReleased: t("tracker.fundReleased"),
      fundUtilized: t("tracker.fundUtilized"),
      utilPercent: t("tracker.utilPercent"),
      variance: t("tracker.variance"),
      pfmsDelta: t("tracker.pfmsDelta"),
      treasuryVariance: t("tracker.treasuryVariance"),
      savedWithWarning: t("tracker.savedWithWarning"),
      // Outcome
      outcomeEntry: t("tracker.outcomeEntry"),
      outcomeEntrySubtitle: t("tracker.outcomeEntrySubtitle"),
      outcomeEntries: t("tracker.outcomeEntries"),
      subject: t("tracker.subject"),
      subComponent: t("tracker.subComponent"),
      kpi: t("tracker.kpi"),
      granularity: t("tracker.granularity"),
      kpiId: t("tracker.kpiId"),
      type: t("tracker.type"),
      periodicity: t("tracker.periodicity"),
      baseline: t("tracker.baseline"),
      value: t("tracker.value"),
      computedPercent: t("tracker.computedPercent"),
      subjectKpiRequired: t("tracker.subjectKpiRequired"),
      hcRequiredDistrict: t("tracker.hcRequiredDistrict"),
      districtRequired: t("tracker.districtRequired"),
    }),
    [t],
  );
}
